version: "3"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && ./bin/dev"
    tty: true
    volumes:
      - .:/app/
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  db:
  node_modules:
